name: Deploy Prisma Migrations

on:
  push:
    branches: [ main ]

jobs:
  prisma-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Setup pnpm
        run: npm ci
      - name: Install dependencies
        run: npm install
      - name: Generate Prisma Client
        run: npx prisma generate --schema=prisma/schema.prisma
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Deploy migrations
        run: npx prisma migrate deploy --schema=prisma/schema.prisma
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Run seed
        run: node prisma/seed.js
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
